[#welcome]
= Welcome

Hello and welcome! 🎉

The goal for this workshop is to give you the tools you need to diagnose performance problems in your Go applications and fix them.

Through the day we'll work from the small -- learning how to write benchmarks, then profiling a small piece of code. Then step out and talk about the execution tracer, the garbage collector  and tracing running applications. The remainder of the day will be a chance for you to ask questions, experiment with your own code.

WARNING: This workshop is not offered by VMware and the opinions expressed within do no necessarily reflect the opinions of VMware. Capeesh?

== Instructors

- Dave Cheney mailto:dave@cheney.net[]

== License and Materials

This workshop is a collaboration between https://twitter.com/davecheney[David Cheney] and https://twitter.com/francesc[Francesc Campoy].

This presentation is licensed under the https://creativecommons.org/licenses/by-sa/4.0/[Creative Commons Attribution-ShareAlike 4.0 International] licence.

== Prerequisites

The are several software downloads you will need today.

=== The workshop repository

Download the source to this document and code samples at {github}

=== Go 1.13

The workshop material targets Go 1.13.
This is currently available in beta.

https://golang.org/dl/#go1.13beta1[Download Go 1.13 beta 1]

NOTE: If you're using Go 1.12 (or maybe 1.11) that's ok.
There are always some small changes to optimisation choices between minor Go releases and I'll try to point those out as we go along.
I'll also highlight the major changes coming in Go 1.13.

[TIP]
====
Go 1.13 won't be released til August.
If you'd like to read more about the upcoming changes here are a few sources for further reading

- https://docs.google.com/presentation/d/e/2PACX-1vRo5urog_B76BcnQbIo7I391MZUKFj7l3gku6hypJ-WK1KCFw40A7BiM6NOVsqD17sA9jS7GyzCfnN4/pub?slide=id.g550f852d27_228_0[What's coming up in Go 1.13] by Daniel Martí
- https://tip.golang.org/doc/go1.13[Go 1.13 draft release notes] (in progress)
====

=== Graphviz

The section on pprof requires the `dot` program which ships with the `graphviz` suite of tools.

- Linux: `[sudo] apt-get install graphviz`
- OSX:
  - MacPorts: `sudo port install graphviz`
  - Homebrew: `brew install graphviz`
- https://graphviz.gitlab.io/download/#Windows[Windows] (untested) 

=== Google Chrome

The section on the execution tracer requires Google Chrome.
It will not work with Safari, Edge, Firefox, or IE 4.01.
Please tell your battery I'm sorry. 

https://www.google.com/chrome/[Download Google Chrome]

=== Your own code to profile and optimise

The final section of the day will be an open session where you can experiment with the tools you've learnt.

== One more thing ...

This isn't a lecture, it's a conversation.
We'll have lots of breaks to ask questions.

If you don't understand something, or think what you're hearing not correct, please ask.